env:
  node: true
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  warnOnUnsupportedTypeScriptVersion: false
ignorePatterns:
  - dist/
  - node_modules/
plugins:
  - '@typescript-eslint'
rules: {}
